spring:
    profiles:
        include:
            - swagger
            - cloudsql
            - debugsql

langer:
    data:
        prefix: qa
        usejpa: false
    security:
        crm-client:
            enabled: true
            secret: asdjfasdkfsldkjfhasdkfh892q38ryshd
        jwt:
            secret: 38782F413F4428472B4B6150645367566B5970337336763979244226452948404D6351655468576D5A7134743777217A25432A462D4A614E645267556A586E32


logging:
    config: 'classpath:logback-web.xml'
