spring:
    jpa:
        properties:
            hibernate:
                format_sql: true
#                show_sql: true
#                use_sql_comments: true
#                type: trace
logging:
    level:
        org:
            hibernate:
                SQL: ERROR
